### ISSUE TITLE
p2p: seed more todo

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1130]
Seed mode has been implemented. Some more things to do:

- [x] TODO https://github.com/tendermint/tendermint/pull/1128#discussion_r162799294
- [x] Should seeds respond with a bias towards good peers ?
- [x] defaultSeedDisconnectWaitPeriod should be at least as long as we expect it to take for a peer to become MarkGood

**Comment by ebuchman** [comment]
Note MarkGood can take 2-3 hours minimum.

**Comment by melekes** [comment]
> Should seeds respond with a bias towards good peers ?

probably, yes. if node connects to seed, it does not have any trusted peers. I guess (especially in the beginning) node should have more trusted peers than untrusted.
