### ISSUE TITLE
consensus: fix tracking for MarkGood

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1317]
As of https://github.com/tendermint/tendermint/pull/1244 we mark peers as good, but the logic there has a bug where peers can send old information that is counted as new. We should only accept new info. 

Also see the other comments from review: https://github.com/tendermint/tendermint/pull/1244#pullrequestreview-104307402
- [x] fix tracking of votes and blockparts to not allow old information
- [x] test the functionality to prove the above is an issue and that it's now fixed
- [x] dont use a magic number for how many blocks we need info from before marking peer as good
- [x] some other things :)

**Comment by ebuchman** [comment]
I'm also worried about changing the panic to a onPeerError here: https://github.com/tendermint/tendermint/pull/1244/files#diff-c46d0aa05757707b7d64e511fbcbe7f5R361

Note that its ok to panic in the onReceive as it's caught in the conn._recover, which does onPeerError.

It might be fine, but we should add a test.

**Comment by ebuchman** [comment]
Booya!
