### ISSUE TITLE
Summary of Upcoming Breaking Changes

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1568]
Proposed summary of impending breaking changes.

The goal is to get as many of the breaking data structure changes into the next breaking release as possible :)

- Change all RIPEMD160 to SHA256[:20]
  - [x] Tx and Validator hashing - #1547, WIP #1606 
  - [x] IAVL (doesn't effect Tendermint)
  - [x] ED25519 address generation - PR tendermint/go-crypto#112

- Don't Amino encode basic byte arrays before hashing
  - [x] Txs - #1547
  - [x] pubkeys when computing addresses - tendermint/go-crypto/#103, PR tendermint/go-crypto#112

- Proposals/Votes - #1146, WIP #1615
  - [ ] ~~don't sign Timestamp~~
  - [ ] ~~instead, we can do BFT time just through the proposer #1615~~ 

- Header
  - [ ] Add proposer (and round?) - #1134
  - [ ] Add tags to results hash - #1007 
  - [ ] NextValSetHash - #1313, WIP #1638

- ABCI
  - [x] AbsentValidators should be a list of addresses, not indices
  - [ ] Update header
  - [ ] Include Round number in BeginBlock (possibly in header as "LastCommitRound" ? )
  - [x] Begin/EndBlock tags - #915
  - [x] ResponseInitChain takes GenesisBytes instead of AppStateBytes - https://github.com/tendermint/abci/issues/216

- Validator set changes 
  - [ ] Validators only change at H+2 - #1313 , WIP #1638
  

- P2P
  - [ ] Update SecretConnection - #1165, #1124, WIP #1563 
  - [ ] Add ValidatorAddress to NodeInfo - #1516, WIP #1604 
  - [x] pubkey -> id in p2p query

**Comment by ebuchman** [comment]
Note also from https://github.com/tendermint/tendermint/issues/1502:

- SignatureKey -> Signature in amino
- Reconcile Query requirements

**Comment by ebuchman** [comment]
Another point still up for debate is what to do about pubkeys in the ABCI (ie. whether or not to involve Amino) -   #1524

**Comment by ebuchman** [comment]
Maybe change LastBlockID to LastBlockHash in the header? https://github.com/tendermint/tendermint/issues/1605

**Comment by ebuchman** [comment]
Ideally the encoding of the header would be compatible with a protobuf encoding - https://github.com/tendermint/tendermint/issues/1605#issuecomment-390828027

**Comment by cwgoes** [comment]
Can we include ABCI evidence updates - https://github.com/tendermint/abci/pull/243 - and the associated Tendermint changes - https://github.com/tendermint/tendermint/pull/1582 - in this changeset?

**Comment by jaekwon** [comment]
While we can have both present and absent validators in BeginBlock, it should be noted that validator updates apply to the next validator set, not the one received via BeginBlock.  This means that ABCI developers should take note to persist the validator set somewhere...

Which kind of defeats the point of using addresses vs indices, imo, since it's easy enough to sort a validator set once you have one.  But that's fine.  I just prefer not to send *both* validator sets to the app via ABCI, because that's "helping" the ABCI developer a little too much to the detriment of performance.

**Comment by ebuchman** [comment]
More changes discussed:

- version in header
- merkle tree of tags for efficient proofs of inclusion/exclusion of tags in a block (rather than putting the tags in the result merkle tree)

**Comment by ebuchman** [comment]
> Which kind of defeats the point of using addresses vs indices, imo, since it's easy enough to sort a validator set once you have one. But that's fine. I just prefer not to send both validator sets to the app via ABCI, because that's "helping" the ABCI developer a little too much to the detriment of performance.

This might turn out to be really unfortunate for devs ... hmm

**Comment by ebuchman** [comment]
Summary of state of this:

## ABCI

- Alot of this was released in v0.11
- We still need to:
  - make the Header match the Tendermint header
  - dont send the pubkey in RequestBeginBlock (see updated ADR https://github.com/tendermint/tendermint/pull/1711) 

## Everything else 

Everything else is basically in open PRs.

## More 

The last thing to work on is how we deal with versioning to facilitate upgrades - both on the blockchain datastructures and in the p2p layer.

I think we need to introduce versions for both these, but not exactly sure how. We should prepare an ADR for how to do this.

**Comment by ebuchman** [comment]
Everything in here is either complete or summarized in open issues that are well tagged.

**Comment by ttmc** [comment]
@ebuchman I realize you closed this issue, but we were using it to get a sense of how many breaking changes we can expect in the future. Could you check the boxes beside the things that are now done and merged? It would also be helpful to check the boxes beside the things that won't ever be done.

**Comment by ebuchman** [comment]
Updated. We're now using the "breaking" tag: https://github.com/tendermint/tendermint/issues?q=is%3Aopen+is%3Aissue+label%3Abreaking

**Comment by ttmc** [comment]
Thanks!
