### ISSUE TITLE
libs/db improvements

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1864]
(three issues from tmlibs)

- [ ] document thread safety-ness in concurrency: https://github.com/tendermint/tmlibs/issues/79
- [ ] re-organize packages: https://github.com/tendermint/tmlibs/issues/207
- [ ] clarify code comment: https://github.com/tendermint/tmlibs/issues/223
