### ISSUE TITLE
Implement Protocol Versions [ADR 016]

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2468]
[ADR-016](https://github.com/tendermint/tendermint/blob/develop/docs/architecture/adr-016-protocol-versions.md)

Subsumes #1627 and #1135 

- [x] Add Version to Header and State - #2644
- [x] Add Version to NodeInfo - https://github.com/tendermint/tendermint/pull/2654
- [x] Remove Version from CanonicalXxx -  #2666
- [ ] Add Version to ConsensusParams so apps can update the App version
- [x] Add Version to ResponseInfo so apps can set initial App version during handshake - #2662
- [x] Update ADR to match - #2667

**Comment by ValarDragon** [comment]
`Add Version to ResponseInfo so apps can set initial App version during handshake` 

We need a way for also upgrading app version mid-execution, right? We earlier proposed making clients have a conditional for switching the app version logic on a certain block height. But at that blockheight their app version should change as well. I think we need another way to communicate that update, since it wouldn't be repeating the node <-> app handshake.

**Comment by ebuchman** [comment]
>  Add Version to ConsensusParams so apps can update the App version

^^
