### ISSUE TITLE
Release 0.8.0

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#300]
v0.8.0

# Summary

- Validator Set changes
- Handshake between Tendermint and App
- BFT-liveness fix
- Way more tests
- TMSP is now ABCI!

# Details 

- Misc
  - Update logging to be less verbose
  - Better test coverage (37% -> 49%)
  - Canonical SignBytes for signable types

- Mempool
  - Write-Ahead Log via go-autofile
  - Fix peer leak

- Consensus
  - Write-Ahead Log via go-autofile
  - Use BlockID = (Hash, PartsHeader) to represent blocks
  - Update Vote structure to include validator address and index
  - New Maj23Msg for peers to alert others they've seen a Maj23, in order to track and handle conflicting votes intelligently to prevent Byzantine faults from causing halts
  - Better in-process testing for the consensus reactor and byzantine faults
  - Fix panic on POLRound=-1
  - Configurable block part set size
  - Validator set changes
  - Set the CommitTime
  - Better abstraction over timeout mechanics
  - Optionally skip TimeoutCommit if we have all the votes

- TMSP
  - TMSP is now ABCI
  - AppendTx is now DeliverTx
  - Send BeginBlock, with Header
  - Handshake and replay for app persistence and recovery

- RPC
  - BroadcastTx via GRPC
  - Hex strings are "0x" prefixed

- Testing
  - More extensive testing of consensus package
  - More crash/restart tests of individual nodes at preset failure points and of networks at arbitrary points

Pull Requests 
- [x] Handshake (Info and BeginBlock) - https://github.com/tendermint/tendermint/pull/265
- [x] BroadcastTxCommit via GRPC - https://github.com/tendermint/tendermint/pull/255
- [x] BFT Vote set changes for - https://github.com/tendermint/tendermint/pull/314
- [x] Validator set changes - https://github.com/tendermint/tendermint/pull/319, https://github.com/tendermint/tendermint/pull/359
- [x] New WAL - https://github.com/tendermint/tendermint/pull/310
- [x] CanonicalJSON sign bytes - https://github.com/tendermint/tendermint/pull/325
- [x] TimeoutTicker and fix tests - https://github.com/tendermint/tendermint/pull/330, https://github.com/tendermint/tendermint/pull/337
- [x] Stability - https://github.com/tendermint/tendermint/pull/337
- [x] Crash/Restart tests -https://github.com/tendermint/tendermint/pull/343
- [x] Optional SkipTimeoutCommit - https://github.com/tendermint/tendermint/pull/360, https://github.com/tendermint/tendermint/pull/362
- [x] Rename AppendTx -> DeliverTx and TMSP -> ABCI - https://github.com/tendermint/tendermint/pull/365

**Comment by ebuchman** [comment]
TODO:

- [ ] fix time dependence in new consensus tests causing CI failures
- [ ] ship builds - https://github.com/tendermint/tendermint/issues/308
- [ ] update block header - https://github.com/tendermint/tendermint/issues/302
- [ ] events issues - https://github.com/tendermint/tendermint/issues/264 and https://github.com/tendermint/go-events/pull/6 
- [ ] Rename AppendTx -> DeliverTx - https://github.com/tendermint/tendermint/issues/245
- [ ] Rename TMSP -> ABCI  (or TSP=teaspoon) - https://github.com/tendermint/tendermint/issues/223
- [ ] Do something with ConfigInfo/TMSPInfo parts of handshake - https://github.com/tendermint/tendermint/issues/211

**Comment by ebuchman** [comment]
Final PRs

- [ ] - https://github.com/tendermint/go-common/pull/6
- [ ] - https://github.com/tendermint/go-db/pull/4
- [ ] - https://github.com/tendermint/go-events/pull/8
- [ ] - https://github.com/tendermint/go-merkle/pull/19
- [ ] - https://github.com/tendermint/go-p2p/pull/11
- [ ] - https://github.com/tendermint/go-rpc/pull/6
- [ ] - https://github.com/tendermint/go-process/pull/1
- [ ] - https://github.com/tendermint/abci/pull/36

In addition we need to see to it that merkleeyes, basecoin, ethermint, and lil-voterin are updated accordingly

**Comment by ebuchman** [comment]
TODO
- [ ] - mintnet
- [ ] - netmon

- [ ] - basecoin
- [ ] - ethermint
- [ ] - merkleeyes
- [ ] - lil-voterin

**Comment by ebuchman** [comment]
https://github.com/tendermint/tendermint/pull/366
