### ISSUE TITLE
temporary

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3684]
- [x] b9508ffec 2019-05-27 [p2p] Peer behaviour test tweaks (#3662) [Ethan Buchman]
- [x] a6ac611e7 2019-05-27 tendermint testnet: Allow for better hostname control (#3661) [Ethan Buchman]
- [x] e7bf25844 2019-05-27 update PULL_REQUEST_TEMPLATE and CONTRIBUTING (#3655) [GitHub]
- [x] bcf10d5ba 2019-05-28 p2p: peer state init too late and pex message too soon (#3634) [Ethan Buchman]
- [x] 5997e75c8 2019-05-23 fix integration script (#3667) [Ethan Buchman]
- [x] 97ceeed05 2019-05-23 Merge pull request #3670 from yutianwu/fix_proxy [GitHub]
- [x] 3ef9e453b 2019-05-23 update change log [yutianwu]
- [x] c7b324d3f 2019-05-23 Merge pull request #3675 from alexanderbez/bez/3672-improve-AddSignatureFromPubKey-error [GitHub]
- [x] cfd42be0f 2019-05-22 Improve error and tests [Aleksandr Bezobchuk]
- [x] f1f243d74 2019-05-21 p2p/pex: consult seeds in crawlPeersRoutine (#3647) [Ethan Buchman]
- [x] fcce9ed4d 2019-05-21 fix lint [yutianwu]
- [x] c21b4fcc9 2019-05-21 fix bug of proxy [yutianwu]
- [x] 86cf8ee3f 2019-05-10 p2p: PeerBehaviour implementation (#3539)  (#3552) [Ethan Buchman]
- [x] 6f1ccb6c4 2019-05-10 [ADR] ADR-36: blockchain reactor refactor spec (#3506) [Ethan Buchman]
- [x] a076b4820 2019-05-07 libs/db: boltdb: use slice instead of sync.Map (#3633) [GitHub]
- [x] a7358bc69 2019-05-07 libs/db: conditional compilation (#3628) [GitHub]
- [x] 27909e5d2 2019-05-07 mempool: remove only valid (Code==0) txs on Update (#3625) [GitHub]
- [x] 1e073817d 2019-05-07 rpc: /dial_peers: only mark peers as persistent if flag is on (#3620) [GitHub]
- [x] 2bb1a87d4 2019-05-07 Merge pull request #3629 from leoluk/fix-boltdb-batch [GitHub]
- [x] d0d9ef16f 2019-05-06 libs/db: fix boltdb batching [Leo]
- [x] 60b833403 2019-05-06 libs/db: close boltDBIterator (#3627) [GitHub]
- [x] debf8f70c 2019-05-06 libs/db: bbolt (etcd's fork of bolt) (#3610) [GitHub]
- [x] 4519ef310 2019-05-05 adr renames (#3622) [GitHub]
- [x] 86f2765b3 2019-05-06 Add adr-36 (#3324) [Ethan Buchman]
- [x] e2f547154 2019-05-05 ADR-037: DeliverBlock (#3420) [Ethan Buchman]
- [x] 4905640e9 2019-05-05 types: CommitVotes struct as last step towards #1648 (#3298) [Ismail Khoffi]
- [x] 4c60ab83c 2019-05-05 Update apps.md (#3621) [Ethan Buchman]
- [x] 5051a1f7b 2019-05-04 mempool: move interface into mempool package (#3524) [GitHub]
- [x] 8711af608 2019-05-03 p2p: make persistent prop independent of conn direction (#3593) [GitHub]
- [x] 9926ae768 2019-05-02 abci/types: update comment (#3612) [Ismail Khoffi]
- [x] 5df6cf563 2019-05-02 p2p: session should terminate on nonce wrapping (#3531) (#3609) [Anton Kaliaev]
- [x] 2c26d95ab 2019-05-02 cs/replay: execCommitBlock should not read from state.lastValidators (#3067) [Ethan Buchman]
- [x] a2a68df52 2019-05-01 cli: add option to not clear address book with unsafe reset (#3606) [Anton Kaliaev]
- [x] 43348022d 2019-05-01 pex: various follow-ups (#3605) [GitHub]
- [x] 40dbad991 2019-04-29 (climber73/develop) pex: dial seeds when address book needs more addresses (#3603) [Anton Kaliaev]
- [x] 258518788 2019-04-26 (CrocdileChan/develop) Merge pull request #3597 from tendermint/bucky/merge-master [GitHub]
- [x] d76952c67 2019-04-26 Merge branch 'master' into bucky/merge-master [Ethan Buchman]
- [x] 7b162f5c5 2019-04-26 node: refactor node.NewNode (#3456) [Anton Kaliaev]
- [x] 70592cc4d 2019-04-26 libs/common: remove deprecated PanicXXX functions (#3595) [Anton Kaliaev]
- [x] 90997ab1b 2019-04-23 docs: update contributing.md (#3503) [Anton Kaliaev]
- [x] b738add80 2019-04-23 cs: fix nondeterministic tests (#3582) [Anton Kaliaev]
- [x] 968e955c4 2019-04-23 testnet cmd: add config option (#3559) [Anton Kaliaev]
- [x] ebf815ee5 2019-04-23 cs/replay: check appHash for each block (#3579) [GitHub]
- [x] 8db7e74b8 2019-04-22 privval: increase timeout to mitigate non-deterministic test failure (#3580) [Anton Kaliaev]
- [ ]
