### ISSUE TITLE
6 Month Objectives (Start July, 2019)

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#3900]
This issue is meant to layout a 6-month roadmap, we have `First Objectives` and `Secondary Objectives`. I will be updating this periodically with updates according to what is finished and being worked on.

The objectives are broken into three categories - Feature, Refactor & Research.

## First Objectives
_Note: the order of the list holds no value_

- [ ] Feature - (ABCI): DeliverBatchTx with configurable batch size. This provides an abstraction that supports both deliverTx and DeliverBlock, thereby enabling apps to use batching and parallel algorithms naturally across txs.
   - [ADR 037: Deliver Block](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-037-deliver-block.md)
- [ ] Feature/Refactor - (Mempool): Allow the application to define its own mempool. Many components of mempool of logic are app-dependent. It would be nice to keep the standard mempool in Tendermint, but allow the app to use a different one. This is needed for mimblewimble like protocols.
- [ ] Feature - (State-sync): StateSync is a feature which would allow a new node to receive a snapshot of the application state without downloading blocks or going through consensus.
  -  [ADR 042: State Sync Design](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-042-state-sync.md)
- [x] Feature/Refactor - (Light Client)
   - [ADR 044: Lite Client with Weak Subjectivity](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-044-lite-client-with-weak-subjectivity.md)
   - https://github.com/tendermint/tendermint/pull/3841
   - https://github.com/tendermint/tendermint/pull/3577
   - *Update*: Lite client has been merged, you can take a peek at within the lite2 pkg
- [ ] Refactor - (Blockchain Reactor): Refactor the Blockchain reactor for better testing.
   - [ADR 040: Blockchain Reactor Refactor](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-040-blockchain-reactor-refactor.md)
  - [ADR 043: Blockhchain Reactor Riri-Org](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-043-blockchain-riri-org.md)
  - *Update*: The reactor is being finalized and preparing to be merged. Currently extensive testing is taking place on testnets and mainnets 
- [ ] Refactor - (Amino): Make amino protobuf compatible
   - https://github.com/tendermint/go-amino
- [x] Refactor/Research- (IAVL): Performance: Investigation & implmentaion
   - https://github.com/tendermint/iavl
   - *Update*: https://github.com/tendermint/iavl/pull/158 is being prepared to merge and used in the cosmos-sdk

### Secondary Objectives
_Note: Secondary objectives are less descriptive but will be expanded on as we progress through the list._
- [ ] Feature - Add dalek backend cryptography to ed25519: performance consideration
   - *Update*: https://github.com/oasislabs/ed25519 is being tested on the cosmos-hub to see what performance gains can be made by using the library
- [ ] Feature - Support using arbitrary hash functions
- [ ] Feature - Better Benchmarking & QA 
  - https://github.com/interchainio/testnets
- [ ] Research - LibP2P exploration
- [ ] Feature - Proposer Selection
- [ ] Empty Block control through end block

**Comment by zmanian** [comment]
Pruning of old blocks should be in here. IMO highest priority after state sync and light client.

Performance of https://github.com/oasislabs/ed25519 should be comparable to dalek.

**Comment by marbar3778** [comment]
Out of the first objectives, the lite client and work on IAVL performance were the two areas that were completed. We managed a lot of cleanup in the codebase and are moving forward with some of the above objectives. 

As for the amino work, we had long discussions around this and are moving forward with proto migrations of the repositories (cosmos-sdk & tendermint) 

State-sync is actively being worked on by @erikgrinaker & @tessr and there is a prototype. If you'd like to follow the progress this ADR is a good place to stay up to date on what is going on https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-053-state-sync-prototype.md.

You may have seen the 2020 roadmap for tendermint core but if you haven't here is the place to find out mroe: https://medium.com/tendermint/tendermint-2020-roadmap-b4709134cff1
