### ISSUE TITLE
encoding: track encoding issues & progress

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#4278]
Currently, Tendermint-Core uses [go-amino](https://github.com/tendermint/go-amino) for the majority of the encoding. If you'd like to read more about the encoding formats in Tendermint-Core please see https://github.com/tendermint/tendermint/issues/608.

We are trying to move go-amino towards full proto3 compatibility.  You can follow this progress here: https://github.com/tendermint/go-amino/issues?q=is%3Aissue+is%3Aopen+label%3Aproto3compat.

The Current open issues within tendermint with encoding are:

- [x] https://github.com/tendermint/tendermint/issues/4241
- [ ] https://github.com/tendermint/tendermint/issues/4208
- [x] https://github.com/tendermint/tendermint/issues/3236
- [ ] https://github.com/tendermint/tendermint/issues/2684
- [ ] https://github.com/tendermint/tendermint/issues/2358
- [ ] https://github.com/tendermint/tendermint/issues/2830
- [ ] https://github.com/tendermint/tendermint/issues/2241

The Migration path we are working on is:

1. Make amino fully proto compatible **(current phase)**
2. Write proto files for all types so that client implmenters can use them
3. Migrate module/reactors to using proto files to encode and decode.

As things progress we will update this issue for everyone to see. 

Modules/Reactors that need to be migrated:

- [x] Blockchain #4637 
- [x] Consensus #4733
- [x] Evidence #4654 
- [x] Privval
- [x] Mempool
- [x] State #4806 
- [x] Statesync
- [x] Store #4778
- [x] p2p
- [x] lite 2 #4762 
- [x] rpc

**Comment by marbar3778** [comment]
The Cosmos-SDK is working towards full proto compatibility: https://github.com/cosmos/cosmos-sdk/issues/5444
