### ISSUE TITLE
evidence: meta issue

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4313]
## Tendermint side (short-term):

- [x] https://github.com/tendermint/tendermint/issues/4214 global evidence spec
- [x] https://github.com/tendermint/tendermint/issues/4213 individual evidence spec (lunatic: https://github.com/tendermint/tendermint/issues/4182)
- [x] https://github.com/tendermint/tendermint/issues/2653 ~~hybrid time & height evidence~~ (PR: https://github.com/tendermint/tendermint/pull/4254) NOTE: cosmos-sdk also needs to make the unbonding period a hybrid of time & height.
- [x] https://github.com/tendermint/tendermint/issues/4530 handle evidence from light client(s)

## Tendermint side (future):

- [x] https://github.com/tendermint/tendermint/issues/4189 Fork-accountability

## Light client (short-term):

- [x] https://github.com/tendermint/tendermint/issues/4215 failure detection spec
