### ISSUE TITLE
State sync release and followup

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#4767]
Tracking issue for state sync (#828) release and followup, now that it has been merged (#4705).

## Before release

- [x] Integrate with v2 blockchain reactor #4765

## At release

- [ ] ~Publish P2P seeds, RPC nodes, and trusted headers #4583~
- [x] Publish ABCI documentation https://github.com/tendermint/spec/pull/90
- [x] Tendermint guide on implementing state sync ([published](https://medium.com/tendermint/tendermint-core-state-sync-for-developers-70a96ba3ee35))
- [x] Cosmos SDK guide on using state sync ([published](https://blog.cosmos.network/cosmos-sdk-state-sync-guide-99e4cf43be2f))
- [x] Merge Cosmos SDK state sync support https://github.com/cosmos/cosmos-sdk/pull/7166
- [x] Merge Gaia state sync support https://github.com/cosmos/gaia/pull/476

## After release

- [ ] Backfill historical blocks #4629
- [ ] Bootstrap node with state machine obtained out-of-band #4642
- [x] Start genesis from non-zero height #2543
- [ ] Allow start with only blockstore #3713
- [ ] Node startup phases #4644 
- [ ] Blog post on Cosmos SDK state sync implementation

**Comment by marbar3778** [comment]
Do we (tendermint eng team / IG) want to run seed nodes or full nodes to provide a easier path for users to initiate state sync for the cosmos hub

**Comment by alexanderbez** [comment]
I think so @marbar3778. It's an excellent idea that has relatively low cost (pretty much just infra) and very good benefit.

**Comment by erikgrinaker** [comment]
Release-related followup tasks are done, closing this since the remaining issues are fairly independent and can be managed separately.
