### ISSUE TITLE
p2p: internal refactor and architecture redesign

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#5670]
As discussed in #2067, the peer-to-peer architecture needs to be redesigned and refactored. The background and scope for this is outlined in [ADR 061](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-061-p2p-refactor-scope.md) (as "phase 1"), and the proposed new architecture design is described in [ADR 062](https://github.com/tendermint/tendermint/blob/erik/adr-p2p-architecture/docs/architecture/adr-062-p2p-architecture.md).

Implementation plan (see ADRs for issue links and further details):

- [ ] Implement `Channel` and `PeerUpdates` APIs as shims on top of current `Switch` and `Peer` APIs, and rewrite all reactors to use them instead.
- [ ] Temporarily duplicate the current `SecretConnection` in the `privval` package until it's replaced by gRPC.
- [ ] Port current `MConnection` code to new `Transport` API, and migrate existing P2P stack to use it.
- [ ] Implement new `peer` and `peerStore` APIs, and make the current address book a shim on top of it.
- [ ] Replace the existing `Switch` abstraction with the new `Router` (possibly split into scheduling and peer lifecycle).
- [ ] Move the PEX reactor and other address advertisement/exchange into the P2P core, possibly `Router`.
- [ ] Clean up reactors and other P2P-related code to make better use of the new abstractions.

**Comment by cmwaters** [comment]
Going to close this as phase I has been completed and phase 2 has been altered given the decision to try implement libp2p.

**Comment by worldisreal** [comment]
@cmwaters Hello, want to know will this https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-062-p2p-architecture.md be formally released with tendermint or not? Any plan? Thanks.
