### ISSUE TITLE
Post-0.34 evidence handling followups [Tracking Issue]

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#5688]
0.34 introduces new kinds of evidence, including evidence submitted by the new light clients. For 0.35, we want to have confidence that all of this evidence is handled as fully as possible. 

Testing work:
- [ ] better unit tests for evidence handling https://github.com/tendermint/tendermint/issues/5942 
- [x] e2e tests including the light client https://github.com/tendermint/tendermint/issues/5935

Needs spec work:
- [ ] https://github.com/tendermint/tendermint/issues/5228 evidence: light client can use genesis state as trusted state 
- [ ] https://github.com/tendermint/tendermint/issues/5270 evidence: handle amnesia attacks

Needs design (implementation) work: 
- [x] https://github.com/tendermint/tendermint/issues/5617 handling evidence when you don't have block history 
- [ ] https://github.com/tendermint/tendermint/issues/4727 control evidence gossiping (has a big question mark still)

**Comment by cmwaters** [comment]
Control evidence gossiping should be reassessed after the p2p refactor is done.

Handling evidence when you don't have the block history is probably the most important of these that we want to reach a conclusion on.

**Comment by tessr** [comment]
Agreed.

**Comment by tessr** [comment]
I think the key issues (reverse sync / e2e testing) have been covered for 0.35. I'm moving this to the next milestone.
