### ISSUE TITLE
Docs master issue

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#580]
- [x] [fix tendermint-types links](https://github.com/zramsay/tendermint/issues/1)
- [x] [deduplicate install files](https://github.com/zramsay/tendermint/issues/2)
- [x] [document where the dummy app comes from](https://github.com/zramsay/tendermint/issues/3)
- [ ] [refactor guides/app-development](https://github.com/zramsay/tendermint/issues/4) 
- [ ] [improve beginner path for docs](https://github.com/zramsay/tendermint/issues/5)
- [x] [improve explanation of what tendermint is](https://github.com/zramsay/tendermint/issues/6)
- [x] [deduplicate contributing](https://github.com/zramsay/tendermint/issues/7)

**Comment by ebuchman** [comment]
can u give these points descriptions so they're not just rando links please
