### ISSUE TITLE
Mempool changes for 0.35 [tracking issues]

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#6410]
The upcoming priority-based mempool work will let applications prioritize certain transactions (e.g., those with a higher fee) in order to help validators choose the right transactions to prioritize/propose when networks are under load. Prior discussion available at https://github.com/tendermint/spec/pull/154.

Priority-based mempool steps:

- [x] ADR written #6368 
- [x] spec update written 
- [x] implementation

Additionally, we have a bunch of open issues for the mempool. Many of those issues will be automatically addressed as part of the refactor, while others should are not necessarily related but should likely be resolved in 0.35 anyways. These likely include: 

- [x] propagate max gas errors back to RPC #3546
- [ ] make mempool.update release a mutex for reap earlier #6232
- [ ] handle out-of-order ABCI responses #5519 
- [ ] filtering duplicate txs #5281 and #3865
- [ ] "full mempool" #3905 - this is also a similar performance issue but I'm not sure if it will be addressed in this refactor

#5281 is the only of these issues that probably _needs_ to be addressed before 0.35 is released; the rest can happen in point releases or later major releases.

**Comment by marbar3778** [comment]
@alexanderbez when you get back from vacation, could you update this issue with anything outstanding.

**Comment by cmwaters** [comment]
@alexanderbez is there anything here we should follow up with? It seems a lot of this work has been deprioritized after 0.35 and we don't really have any plans to continue with it in the near future unless you think otherwise.
