### ISSUE TITLE
tracking: improve tooling for build, test, and developer experience

### ISSUE THREAD

**Issue by tychoish** [tendermint/tendermint#6416]
## Context

Currently there's a lot of disctint build and packaging logic in the Tendermint repository to take care of build, test, and release automation. This code is divided by a collection of Dockerfiles, Makefiles, shell scripts, and small go programs. This is both difficult to maintain but also makes the learning curve for contributing (at any level) to tendermint. 

## Objectives

This ticket tracks a body of work to refactor and modernize all of the build and project infrastructure, with the following high-level goals: 

- eliminate CGo dependencies, so that reproducible tendermint builds are possible without Docker. 

- combine separate go binaries into a single multi-command (a la git) to reduce the build complexity, and centralize build configuration to reduce the number of makefiles and simplify the that logic as much as possible

- provide a common and idiomatic interface for executing tests to reduce the number of ways to run tests during development (for example, operationalize benchmarks and make e2e tests "feel" more like regular tests.)

- in CI, improve reporting for tests to track timing and test outcomes over time, as well as make it easier for developers to identify and reproduce test failures, and identify patterns in test failures over time.

## Tasks

(Still limited)

- [ ] [related] #6404 benchmarking improvements 
- [ ] [dependency] #6032 database improvements
- [ ] #6373 - cmd: integrate e2e test commands 
- [ ] Consider using [gotestsum](https://github.com/gotestyourself/gotestsum) to improve test output.
- [ ] Capture more useful logging during tests to improve debugability.
- [ ] Rationalize command line interface and combine arbitrary related binaries.
- [ ] Combine/reduce  Makefiles, and scope of responsibility.
- [ ] (possibly) remove use of docker in build and test

**Comment by augchan42** [comment]
More basically, doing a make fails immediately as the check target is not defined in the makefile

osboxes@osboxes:~/tendermint$ make
make: *** No rule to make target 'check', needed by 'all'.  Stop.
osboxes@osboxes:~/tendermint$
