### ISSUE TITLE
Some tutorials link to files in the master branch instead of their version branch

### ISSUE THREAD

**Issue by creachadair** [tendermint/tendermint#7675]
A follow-up to #7674.

A number of Markdown files in the docs directory, notably the tutorials, link to versions of files at the tip of the master branch instead of the version for which the tutorial is generated.  This gives confusing results on the doc site, where the actual contents (and sometimes locations) of files may have diverged on the development head.

It would be nice to automate branching this in some way, since the values may change between versions even within a release branch.

### Work Items

- 🆗 ~Fix up absolute links that point to docs.tendermint.com/master/spec.~ (we wound up backing out the removal of docs from master, so this is now moot)
- [x] Fix up links imported from the spec repo to point to tendermint/tendermint (#7851).
- [x] Rewrite the branch-based links on v0.33.x (#7887), v0.34.x (#7871), and v0.35.x (#7870) to target their branch.
- [x] Drop master from the generated docs site entirely (#7874).
- [x] Remove RFC and ADR documents from v0.33.x (#7879), v0.34.x (#7867), and v0.35.x (#7866).
- [x] Add to the release docs a step: When cutting a new backport branch, do the same path rewriting for that backport branch (#7846).

**Comment by creachadair** [comment]
Fixing this turns out to be a little more complicated than it appears.

The advice from [`DOCS_README.md`](../blob/master/docs/DOCS_README.md) is that "Relative links should be used nearly everywhere", because it "works both on GitHub and for the VuePress build". The latter is true, but unfortunately insufficient.

The specific problem is that the docs site is rooted at the `docs` directory, not the root of the repo. So links to other documentation pages need to be relative to that. However, because of the different rooting, links to _other_ repository files _cannot_ be made relative, because they traverse past the root of the URL.

So we can fix the targeting of links within the doc site, but not outside it.

We might be able to fix this for the docs site build by tweaking the VuePress config (e.g., inserting placeholders and substituting them for the target branch during the build). If we do that, however, then the links _within_ the repository will no longer work, which will break markdown link checking and various other automation (along with readers' ability to move around when navgiating the repo on GitHub).

**Comment by cmwaters** [comment]
Why is it not possible to use absolute URL's for links outside the docs directory? 

Is this just a problem because we copy the entire spec across?

**Comment by creachadair** [comment]
> Why is it not possible to use absolute URL's for links outside the docs directory? 
> 
> 
> 
> Is this just a problem because we copy the entire spec across?

That is what we do now. The problem with absolute links is that they require embedding the branch name to form the URL. Presently, we do that using master, which means the docs site points to the master copy regardless of which version is selected, and master diverges from what is in the docs for previous versions. 

If we stub in a placeholder for vuepress to rewrite, then those links will appear as broken when viewed from GitHub directly, which means they'll fail in the link checker.

**Comment by creachadair** [comment]
> So one option could be that whenever we create a backport branch we also update the docs to shift away from master and now to the backport branch?

Yes. That's what I'm leaning toward. It wouldn't be hard to script rewriting URLs that point to the master branch of some file to target the backport branch instead. It would need to be done after creating the branch (of course) and committed against it before cutting a release. 

> I'm not even convinced we should have documentation for master anyway since everything's in flux and we recommend people to use versions

That's a reasonable take. I don't have a strong feeling about keeping master on the doc site, but I would prefer that links viewed on GitHub continue to work when viewing the master branch.

**Comment by creachadair** [comment]
I believe this is now done.
