### ISSUE TITLE
spec: port abci++ spec to main

### ISSUE THREAD

**Issue by jmalicevic** [tendermint/tendermint#9201]
We need to port the abci++ spec from 0.36.x to main. The version of ABCI++ that will be released in 0.37 does not contain all the features described in the existing spec and we need to remove the corresponding content.

- [x] Copy current state of ABCI++ spec on v0.36.x onto `feature/abci++ppp` 
- [x] remove references to unused features: vote extensions, FinalizeBlock (type of work similar to https://github.com/tendermint/tendermint/issues/7745) 
- [x] Remove global client mutex (https://github.com/tendermint/tendermint/issues/7073) won’t be picked up for risk mitigation → “revert” the spec accordingly
- [x] Follow code-related hunks of (https://github.com/tendermint/tendermint/pull/8796)
- [x] Update the spec to contain the same information added to speci/abic (see #9182  )
- [x] Update PrepareProposal API to contain just a list of bytes (see #9283 )

**Comment by jmalicevic** [comment]
All items were added to the specification and merged into master.
