### ISSUE TITLE
backport: Add p2p security fix to v0.34 and v0.37

### ISSUE THREAD

**Issue by jmalicevic** [tendermint/tendermint#9517]
This is a ToDo issue for backporting and testing the security fix from #9500. 

**v0.34**
- [x]  Backport v0.34.x and add a CHANGELOG_PENDING.md #9516 
- [x] Run a large-scale testnet (a single test) on v0.34.x with this fix and check that things work as expected.
- [x] Cut v0.34.22.

**v0.37**
- [ ] Backport to v0.37.x and add a CHANGELOG_PENDING.md  #9515
- [ ] Keep the v0.37.x backport branch open until we've cut v0.37.0, then merge it.
- [ ] Run another large-scale testnet on v0.37.x to check that things work before cutting v0.37.1.
