### ISSUE TITLE
Tracking issue for more aggressive removal of bad peers

### ISSUE THREAD

**Issue by jmalicevic** [tendermint/tendermint#9545]
### Description

This issue aims to cover a wide variety of use cases where Tendermint could remove bad peers more proactively. Peer removal is triggered by information from various reactors and  aims to a) increase security and b) boost performance. 

There are already a number of issues created around this topic. 

### Definition of done 
- Define and specify bad peer behaviour. By bad behaviour we do not necessarily mean malicious behaviour. Rather, peers can be considered bad if they are slow, sending stale or unwanted messages or  too frequent requests. Each issue tackling peer removal has to clearly identify what behaviour is considered bad. 
- Node is disconnected from peers upon detection of bad behaviour. 
- Changes are backported to 0.34.x
- Changes are backported to the latest 0.37 version
- QA tests are performed for each backport before release. 

#### Mempool
- [ ] Removing transactions failing CheckTx. #6523
- [ ] Allow application to return a code in CheckTx marking a transaction that never could have been valid, leading to a disconnect from the peer who sent this transaction. 
   - [x] #9546
          - The use case where a node sends transactions that could never have been valid;
Implications on the security and correctness model of Tendermint (how does the application know that it is this particular peer that should be removed, is this scenario not covered already by other layers in Tendermint, etc.);
          - What other changes in other parts of Tendermint should the implementation of this require;
          - If solution/problem still seem valuable, propose an implementation path taking into account potential need to refactor and change the p2p layer itself to support this.
   - [ ] Implement peer removal based on return code from CheckTx.
           #7918  
           #2185
#### Consensus
- [ ] #2871
- [ ] #6118

#### Blocksync
- [ ] #2896

#### Pex/p2p
- [ ] #3081
- [ ] #4754

**Comment by jmalicevic** [comment]
I agree, but that also depends on the exact changes implemented. Some of these issues are adding checks for additional errors but other changes might be more complex. I think its better to leave it in the description and if we decide not to do it for a potential case, we can explain why this is not done.
