### ISSUE TITLE
Bandwidth optimization

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9880]
High-level tracking issue for general bandwidth optimization efforts. This issue can be expanded over time.

At present (late 2022), Tendermint-based networks consume large quantities of bandwidth, which results in high operational costs for larger networks. We aim to explore ways of bringing down bandwidth consumption while maintaining correctness, with the aim of reducing these costs.

- [ ] Release v0.34.25 with the changes from #9760
  - [ ] First implement #9928 to validate that it's compatible with existing networks
- [ ] Investigate what kind of data is consuming the most bandwidth
  - [x] #9706 ([Rendered RFC](https://github.com/tendermint/tendermint/blob/main/docs/rfc/rfc-027-p2p-message-bandwidth-report.md))
  - [x] #9922
- [ ] Implement quick fixes and improvements to reduce bandwidth consumption (this task will be updated using the results of #9922 )
  - [x] #9760 (to be released in v0.34.25)
- [ ] Investigate protocol change options for more substantial bandwidth optimization
  - [x] #9923
  - [x] #9924
  - [x] #9925
- [ ] Implementation of chosen optimizations (this task will be refined using as input the results of #9923, #9924, #9925)
  - [ ] Propose ADR for protocol changes
  - [ ] Update specs for protocol changes
  - [ ] Implement protocol changes
  - [ ] Update docs for protocol changes

### References
- #9575 (efforts toward bandwidth improvements in Q4-2022)

**Comment by sergio-mena** [comment]
For reference, #9575 has a detailed description of the efforts made to optimize bandwidth in Q4-2022
