### ISSUE TITLE
Storage optimization

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9881]
High-level tracking issue for general storage optimization efforts. This issue can be expanded over time.

At present (late 2022), depending on their configuration, Tendermint-based nodes use large quantities of storage space. This has significant cost implications for operators. We aim to implement strategies to reduce and/or offload certain data stored in order to reduce operators' costs.

- [ ] Investigate which types of data are consuming the most storage space
  - [ ] Provide a way to obtain a clear breakdown of the different types of data a node is storing and how much storage they use. 
- [ ] #9943 Preliminary investigation to identify the users and workloads of the storage backend. The result of this step is supposed to be a high level list containing information on who and how (at a very high level) accesses the storage.
    - [ ] What components of Tendermint access the storage and how do they access it (read/write)
    - [ ] How are our users interacting with the storage (operators, relayers etc.) 
- [ ] Extend the previous point with: #9773
     - [ ] Define the metrics we need to understand the usage of storage. 
     - [ ] Implement the metrics defined.
- [x] #9749 
     - [ ] Gather data using previously implemented metrics to identify the storage requirements for Tendermint. 
     - [ ] Research different databases based on the obtained requirements. 
     - [ ] Refactor Tendermint to use a single database backend. 
 - [ ] Identify the functionalities we want to support within Tendermint and offload non-critical data and functionality
     - [ ] #9437
     - [ ] Provide a mechanism to offload event indexing based on #9437 or a different design.
- [ ] Short-term fixes to alleviate pressure for operators
  - [x] #9743 
  - [ ] #8458
- [ ] Develop an understanding on how to manage a blockchain's history across the whole network
- [ ] Storage management is complex (a UX/docs-related set of problems)
  - [x] #9906
