### ISSUE TITLE
Rolling out new functionality faster, but reliably

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9882]
High-level, multi-quarter tracking issue for specific work aiming to make the codebase more malleable, while maintaining high standards in terms of QA. This issue will be expanded over time.

The ecosystem benefits from changes to Tendermint relatively slowly. This is partially due to the sheer complexity and entanglement of various parts of the codebase as it has evolved somewhat organically over the years.

- [ ] Having clear specifications will allow us to modularize the system better, which we believe will allow us to make changes more easily:
  - [ ] #9321 
- [ ] Improving our QA will give us greater confidence when making changes
  - [ ] #9580 
  - [x] #9937
  - [ ] Add CI workflows to give better assurances with every pull request
    - [ ] Automatically flag Go API-breaking changes on release branches
    - [ ] #8003
    - [x] #9872 
- [ ] Better testing for user-facing parts of the system
  - [ ] Ensure that all breaking RPC changes are deliberate
- [ ] Automation and streamlining of upgrade processes
  - [ ] #5680
  - [ ] Add automated upgrade tests to our QA for new major releases

### Related:

- Making the system more modular should lend itself to being able to make changes more easily
  - #9878 
- Offloading non-critical data will allow us to simplify the node architecture
  - #9437
