### ISSUE TITLE
Improvements for integrators

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9883]
High-level tracking issue for improvements targeting users who want to integrate with Tendermint-based nodes. This issue will be expanded over time.

Integrators currently make use of several surfaces/APIs of a Tendermint-based node in order to provide value-added services on top of those nodes. We want to provide ways to make integrators' lives easier.

This issue does _not_ cover the Go APIs. For improvements targeting the Go APIs, please see: #9878 

- [ ] Make consuming Tendermint's Protobuf definitions easier
  - [ ] Restructure Protobuf usage in Tendermint: https://github.com/tendermint/tendermint/issues/9197#issuecomment-1332956463
  - [ ] #9197 
- [ ] Provide better quality, standards-compliant APIs
  - [ ] #9751 
  - [ ] #7157 
  - [x] #9949
  - [ ] #9256 
- [ ] Allow for reliable offloading of data to companion services (e.g. independently scalable RPC services)
  - [ ] #9437

**Comment by tac0turtle** [comment]
I would also propose looking into how to reduce the number of forks. Talking to teams that have forks and helping reduce the maintenance load for them will enable a more secure tendermint ecosystem

**Comment by thanethomson** [comment]
> I would also propose looking into how to reduce the number of forks.

The scope for this particular issue is people integrating with Tendermint's external APIs (RPC, P2P, etc.). For our high-level priority regarding addressing this issue, please see #9878.

**Comment by thanethomson** [comment]
Thinking about it now though, I suppose if Tendermint's external APIs are inadequate, then people have to fork to implement their own APIs.
