### ISSUE TITLE
Enabling new use cases for application developers

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9886]
High-level tracking issue for 2022-2023 efforts toward enabling new use cases for application developers.

Tendermint's ABCI model has been quite successful thus far, but suffers from some limitations that we believe could be overcome by ABCI 2.0 (a.k.a. ABCI++).

- [x] ABCI 1.0 with Prepare/ProcessProposal in Tendermint v0.37 (see #9091)
  - [x] #9053
- [ ] ABCI 2.0 built on top of 1.0, with FinalizeBlock and Vote Extensions, in Tendermint v0.38 (see #9428)
  - [ ] #9396
- [ ] ABCI 3.0 and other non-urgent improvements
  - [ ] #8458
  - [ ] #8233
  - [ ] #7750
  - [ ] #8498
  - [ ] #8565
- [ ] Planned improvements for state sync
  - [ ] Familiarize with the differences between state sync in `v0.36.x` and `main`
  - [ ] Backport those differences that we deem necessary, e.g., adding a p2p-based state provider
  - [x] #9946
  - [ ] Investigate potential bugs in statesync - (ex. suspect that nodes sending snapshots which contain 0 chunks).
