### ISSUE TITLE
Integrate divergences between cherry-picked implementation and manual work in #9620

### ISSUE THREAD

**Issue by sergio-mena** [tendermint/tendermint#9887]
This issue tracks the progress in integrating the divergences detected between the vote extension implementation in branch `feature/abci++vef` (backported from `v0.36.x` and #9620 (which was done manually)

Some of the divergences have turned out to be quite involved so I will be submitting several PRs to keep separation of concerns.

- [x] Easy ones / Obvious bugs: #9888
- [x] Refactor `MakeVote` and `signAddVote`: #9895
- [x] Handling of vote extension activation in the blocksync reactor (and possibly the bug Anoma hit this summer) #9926
- [ ] Other/remaining #9927

**Comment by sergio-mena** [comment]
Closed by #9988, #9895, #9926, #9927
