### ISSUE TITLE
ABCI 2.0: Final adjustments

### ISSUE THREAD

**Issue by sergio-mena** [tendermint/tendermint#9916]
Tasks:

  - [x] #9954
  - [ ] Protobuf: responses should be enums: see what is missing from #8158 [Estimation: 0.5 days]
  - [ ] Block data exposed to App: follow #8216 and take the parts still missing (mainly `FinalizeBlock`) [Estimation: 1 day]
  - [ ] Double-check if there is something we need from #8414 (probably not)
  - [ ] See what metrics we are still missing from #8480 (mainly vote extensions)
  - [ ] Redundant params in `FinalizeBlock`, and obsolete methods (`BeginBlock`, etc). Double check that changes in #8598 and/or #8633 are unnecessary
  - [ ] Move `app_hash` from `Commit` to `FinalizeBlock`: follow #8664
  - [ ] Compare the status of abci's `types.proto` in `feature/abci++vef` and `v0.36.x` and make sure no changes are related to vote extensions and `FinalizeBlock`
  - [ ] #8206
  - [ ] #9002
  - [ ] [Optional]: Run a testnet on DO (200 node test) as smoke test on this branch
  - [ ] Once we are code complete, and all CI tests pass, merge branch back into `main`
  - [ ] Fix and unit-test condition `vote.Height < 0` in Vote::ValidateBasic in `v0.37.x` and `v0.34.x`

DoD:

  - No errors in CI
  - No major concerns if testnets were run
  - Branch `feature/abci++vef` has been merged back into `main`
